### ISSUE TITLE
DJI Forum Logins Broken

### ISSUE THREAD

**Issue by pquimby** [dji-sdk/Mobile-SDK-Tutorial#11]
We cannot log into the DJI forums to post bug reports or make other comments. The login process redirects to the account summary page, but going back to the forums doesn't solve anything. We don't have a useful way to file a bug other than here.

**Comment by ShuoYangRobotics** [comment]
Hi we temporarily have a server problem. It will be fixed today. I will notify you once the server is ready

**Comment by oliverou** [comment]
Since this issue was resolved, close it now.
