### ISSUE TITLE
Tutorial doesn't work in newest Mobile Version SDK

### ISSUE THREAD

**Issue by kendemu** [dji-sdk/Mobile-SDK-Tutorial#25]
This tutorial doesn't work in newest Mobile Version SDK released in 2015-9-25. I get simbol error in ConnectToDrone() API Call. When will the new tutorial be updated?

**Comment by dji-dev** [comment]
Hi, we have updated Android FPVDemo demo to SDK 3.0, please check if it works, thanks!

**Comment by oliverou** [comment]
For Android tutorial, currently only Android FPVDemo has updated to SDK 3.0. For other tutorials, we will update them soon. Close the issue now.
