### ISSUE TITLE
No file for Android Creating a Camera Application

### ISSUE THREAD

**Issue by wilsonmar** [dji-sdk/Mobile-SDK-Tutorial#26]
There is no FPVDemo_en.html file in https://github.com/dji-sdk/Mobile-SDK-Tutorial/tree/master/en/Android/FPVDemo

So links to https://dji-dev.gitbooks.io/mobile-sdk-tutorials/content/en/Android/FPVDemo/FPVDemo_en.html  would result in a 404 Not found error. 

The Gitbook menu is grayed out.

**Comment by oliverou** [comment]
Hi, already fix this issue, close it now.
