### ISSUE TITLE
Toast called in new Thread()

### ISSUE THREAD

**Issue by viralsavani** [dji-sdk/Mobile-SDK-Tutorial#4]
Toast is called within new Thread(), it would cause and exception as UI would not be reachable through this thread. Change it with:

``` java
runOnUiThread(new Runnable() {
    public void run() {
        Toast.makeText(getApplicationContext(), "activation success", Toast.LENGTH_SHORT).show();
    }
});
```

OR

Use the Logger to log the result if showing the result in not mandatory.

``` java
Log.e(TAG, "onGetPermissionResult = "+result);
Log.e(TAG, "onGetPermissionResultDescription = "+DJIError.getCheckPermissionErrorDescription(result));
```

**Comment by mrjzhao** [comment]
It seems in the demo Toast is called through the handler messages. Would you please show the detail about the place where Toast is called within new Thread()?

**Comment by mrjzhao** [comment]
The problem has been revised
